name = "website"
account_id = "5e565cf9fa55b0eae1f8131903da2ca9"
compatibility_date = "2026-07-10"
compatibility_flags = ["nodejs_compat"]
preview_urls = true

[observability]
enabled = true

[vars]
NUXT_PUBLIC_SITE_URL = "https://bas.dev"
