export {
    faCss3,
    faDribbble,
    faFacebook,
    faGitAlt,
    faGithub,
    faHtml5,
    faInstagram,
    faJava,
    faJs,
    faLinkedin,
    faMicrosoft,
    faNodeJs,
    faPhp,
    faReact,
    faSnapchat,
    faSwift,
    faTwitter,
    faVuejs,
    faWordpressSimple
} from '@fortawesome/free-brands-svg-icons';
